// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7hLw5Nhkj8_XAP8XxLfiHjn9vd0SWBDo',
    appId: '1:692135151812:web:2f14f61e0cfe16e63ae191',
    messagingSenderId: '692135151812',
    projectId: 'travelapp-5ce18',
    authDomain: 'travelapp-5ce18.firebaseapp.com',
    storageBucket: 'travelapp-5ce18.appspot.com',
    measurementId: 'G-FHH5M9K2C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvhn4V5DqSFQFW8k4opgJSDsoBEEVh40c',
    appId: '1:692135151812:android:32fc3aa7d43e45703ae191',
    messagingSenderId: '692135151812',
    projectId: 'travelapp-5ce18',
    storageBucket: 'travelapp-5ce18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA66pPVEUmIkAfnn9xBi4D0m3YSvNp4prc',
    appId: '1:692135151812:ios:f8bd304cad5e92053ae191',
    messagingSenderId: '692135151812',
    projectId: 'travelapp-5ce18',
    storageBucket: 'travelapp-5ce18.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA66pPVEUmIkAfnn9xBi4D0m3YSvNp4prc',
    appId: '1:692135151812:ios:f8bd304cad5e92053ae191',
    messagingSenderId: '692135151812',
    projectId: 'travelapp-5ce18',
    storageBucket: 'travelapp-5ce18.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7hLw5Nhkj8_XAP8XxLfiHjn9vd0SWBDo',
    appId: '1:692135151812:web:04641f4fbf369c893ae191',
    messagingSenderId: '692135151812',
    projectId: 'travelapp-5ce18',
    authDomain: 'travelapp-5ce18.firebaseapp.com',
    storageBucket: 'travelapp-5ce18.appspot.com',
    measurementId: 'G-94SZGB5M2Q',
  );
}
